platform :ios, '8.0'

target 'Example' do
  pod 'BitTorrent/Downloader', :path => '..'
end

# For development pod
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["HEADER_SEARCH_PATHS"] ||= ['$(inherited)']
      config.build_settings['HEADER_SEARCH_PATHS'] << '../../include'
    end
  end
end
